### PR TITLE
Optimized and added some features

### PR DESCRIPTION
**Pull request by 27px**
1. Converted words in json file to uppercase
2. Optimized validation of 'is guessed word in json array', so no need to loop through array and convert every word to upper case to check if word is in array.
3. Fixed erroring out when Ctrl+C is pressed to terminate program, Previously if you press shortcut ctrl+c while playing the game, to terminate program, an unhandled exception was thrown, now it exits normally with a good bye message.
4. Added feature to check if word already entered, you cannot enter same word twice in one game.

### CODE REVIEW

**Comment by burkeholland** [comment]
Keeps getting better and better!

**Comment by burkeholland** [comment]
Oh - uh, optional chaining doesn't work in Node LTS. We _could_ move to TypeScript. Cause otherwise the solution is to just do it in the main method.

**Comment by 27px** [comment]
ok

**Comment by 27px** [comment]
For now we can use try-catch as an alternative. Fixed it in #5

**Pull request merged**
